#!/usr/bin/env bash
# Runs the generated experiments of the transfer-conditions study (item 2).
#
#   ./run_item2.sh                 # step1 m1 m2 m3
#   ./run_item2.sh m1 m3           # only some groups
#
# Configs are (re)generated by analysis/generate_runs.py. An experiment that finished
# successfully leaves logs/item2/<experiment_name>.done and is skipped next time, so the script
# can be re-launched after an interruption; delete that .done file to force a rerun.

set -uo pipefail
cd "$(dirname "$0")" || exit 1

PY="${BR2IDGE_PYTHON:-python}"
SELECTED=("$@")
[ ${#SELECTED[@]} -eq 0 ] && SELECTED=(step1 m1 m2 m3)

"$PY" analysis/generate_runs.py "${SELECTED[@]}" || exit 1
mkdir -p logs/item2

FAILED=()
for g in "${SELECTED[@]}"; do
    for cfg in runs/"$g"/*.json; do
        name=$("$PY" -c "import json,sys; print(json.load(open(sys.argv[1]))['experiment_name'])" "$cfg")
        done_flag="logs/item2/${name}.done"
        if [ -f "$done_flag" ]; then
            echo "[skip] $name (already finished)"
            continue
        fi
        log="logs/item2/${name}.log"
        echo "[run]  $name  -> $log"
        if "$PY" framework.py --config "$cfg" > "$log" 2>&1; then
            touch "$done_flag"
        else
            echo "[FAIL] $name (see $log)"
            FAILED+=("$name")
        fi
    done
done

echo
if [ ${#FAILED[@]} -gt 0 ]; then
    echo "Failed: ${FAILED[*]}"
    exit 1
fi
echo "All experiments finished. Bring back: artifacts/beir_nfcorpus artifacts/msmarco_trec_dl logs/item2"
